import { Navbar } from "@/components/Navbar";
import { Inter } from "next/font/google";
import Head from "next/head";
import styles from "../styles/MainLayout.module.css";
const inter = Inter({ subsets: ["latin"] });

import { ReactNode } from "react";

export const MainLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Principal - N5 Now | Carlos Echeverría</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>N5 Now project</h1>
        <h2 className={inter.className}> Listado de personajes</h2>
        { children }
      </main>
    </>
  )
};
